name: frontend-runner
on:
    push:
      branches:
        - master
      paths:
        - 'dist/stuvatar/**'
    workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
            echo $(ls)
