name: frontend-runner
on:
    push:
      branches:
        - master
      paths:
        - 'dist/stuvatar/**'
    workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
            ls > ~/test.log
